// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6VWkz_f59hJEIGGpeq7WNV185eJHtZg',
    appId: '1:133768705314:web:50c15a6a65680a04a4e17b',
    messagingSenderId: '133768705314',
    projectId: 'jj-on-fire-8bd71',
    authDomain: 'jj-on-fire-8bd71.firebaseapp.com',
    storageBucket: 'jj-on-fire-8bd71.appspot.com',
    measurementId: 'G-R4GEX58YGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRcVvTvnWNmeO_1sPGZJY7EujlwtMcG-I',
    appId: '1:133768705314:android:a681e355977812fca4e17b',
    messagingSenderId: '133768705314',
    projectId: 'jj-on-fire-8bd71',
    storageBucket: 'jj-on-fire-8bd71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGGMhU29nuua-FVVjU_xwmuTFpNKLnf78',
    appId: '1:133768705314:ios:2b6d7687bd802635a4e17b',
    messagingSenderId: '133768705314',
    projectId: 'jj-on-fire-8bd71',
    storageBucket: 'jj-on-fire-8bd71.appspot.com',
    iosBundleId: 'com.example.dailyCatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGGMhU29nuua-FVVjU_xwmuTFpNKLnf78',
    appId: '1:133768705314:ios:66431d13f9a58247a4e17b',
    messagingSenderId: '133768705314',
    projectId: 'jj-on-fire-8bd71',
    storageBucket: 'jj-on-fire-8bd71.appspot.com',
    iosBundleId: 'com.example.dailyCatsApp.RunnerTests',
  );
}
